[package]
name = "mathcat_c"
version = "0.2.0"
authors = ["Neil Soiffer <soiffer@alum.mit.edu>"]
edition = "2021"
license = "MIT"
description = "C/C++ interface for MathCAT (for MathCAT info, see crates.io or nsoiffer.github.io/MathCAT)"


[dependencies.mathcat]
version = "0.2.1"
# for testing MathCAT without having to publish a new version (change two occurences)
# path = "../MathCAT/"

[lib]
name = "libmathcat_c"
crate-type = ["cdylib"]      # Creates dynamic lib
#crate-type = ["staticlib"] # Creates static lib

[build-dependencies]
zip = { version = "0.6.2", default-features = false, features = ["deflate"] }
cbindgen = "0.20.0"
mathcat = "0.2.1"
# for testing MathCAT without having to publish a new version (change two occurences)
# mathcat = {path = "../MathCAT/"}

[profile.release]
debug = true
lto = true
# opt-level = "z"  # Optimize for size.
