[package]
name = "mathcat_c"
version = "0.1.0"
authors = ["Neil Soiffer <soiffer@alum.mit.edu>"]
edition = "2021"

[dependencies.mathcat]
version = "0.1.23"
# for testing MathCAT without having to publish a new version (change two occurences)
# path = "../MathCAT/"

[lib]
name = "libmathcat_c"
crate-type = ["cdylib"]      # Creates dynamic lib
#crate-type = ["staticlib"] # Creates static lib

[build-dependencies]
zip = { version = "0.6.2", default-features = false, features = ["deflate"] }
cbindgen = "0.20.0"
mathcat = "0.1.23"
# for testing MathCAT without having to publish a new version (change two occurences)
# mathcat = {version= "0.1.23", path = "../MathCAT/"}

[profile.release]
lto = true
# opt-level = "z"  # Optimize for size.
